/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "SwaggerUI": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "User": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
